version: '3.8'
services:
    oai-nr-ue1:
        image: oai-nr-ue:develop
        privileged: true
        container_name: rfsim5g-oai-nr-ue1
        environment:
            RFSIMULATOR: 172.17.0.1         # Resolve to "localhost" on host machine
            FULL_IMSI: '001010000000001'
            FULL_KEY: 'fec86ba6eb707ed08905757b1bb44b8f'
            OPC: 'C42449363BBAD02B66D16BC975D77CC1'
            DNN: oai
            NSSAI_SST: 1
            # Use options to pass nssai_sd, otherwise the s_nssai does not match AMF's support list
            USE_ADDITIONAL_OPTIONS: --sa --rfsim -r 106 --numerology 1 --band 78 -C 3619200000 --nokrnmod --uicc0.nssai_sd 1 --uecap_file /opt/oai-nr-ue/etc/uecap.xml --log_config.global_log_options level,nocolor,time
        networks:
            public_net:
                ipv4_address: 192.168.71.150
        volumes:
            - ../../../targets/PROJECTS/GENERIC-NR-5GC/CONF/uecap.xml:/opt/oai-nr-ue/etc/uecap.xml
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5

    oai-nr-ue2:
        image: oai-nr-ue:develop
        privileged: true
        container_name: rfsim5g-oai-nr-ue2
        environment:
            RFSIMULATOR: 172.17.0.1         # Resolve to "localhost" on host machine
            FULL_IMSI: '001010000000002'
            FULL_KEY: 'fec86ba6eb707ed08905757b1bb44b8f'
            OPC: 'C42449363BBAD02B66D16BC975D77CC1'
            DNN: oai
            NSSAI_SST: 1
            # Use options to pass nssai_sd, otherwise the s_nssai does not match AMF's support list
            USE_ADDITIONAL_OPTIONS: --sa --rfsim -r 106 --numerology 1 --band 78 -C 3619200000 --nokrnmod --uicc0.nssai_sd 1 --uecap_file /opt/oai-nr-ue/etc/uecap.xml --log_config.global_log_options level,nocolor,time
        networks:
            public_net:
                ipv4_address: 192.168.71.151
        volumes:
            - ../../../targets/PROJECTS/GENERIC-NR-5GC/CONF/uecap.xml:/opt/oai-nr-ue/etc/uecap.xml
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    public_net:
        driver: bridge
        name: rfsim5g-oai-public-net
        ipam:
            config:
                - subnet: 192.168.71.128/26
        driver_opts:
            com.docker.network.bridge.name: "rfsim5g-public"
